# auto generated by "smithed_librairies/packs/crafter.py" at build time
# commands in order :
# - data modify storage smithed.crafter:main root.temp.item_tag set value []
# - execute
#       if predicate smithed.crafter:block/table/tags/acacia_logs
#       run data modify storage smithed.crafter:main root.temp.item_tag append value "#minecraft:acacia_logs"
# - (...) (part auto generated by "smithed_librairies/packs/crafter.py" at build time)
# - function #smithed.crafter:event/query_tags
