extend: "@smithed_libraries/common.yaml"

id: smithed.crafter
name: Smithed Crafter
version: "0.2.0"
description: Native Library for Smithed
author: TheNuclearNexus

data_pack:
  name: Smithed Crafter
  load: .
      
resource_pack:
  name: Smithed Crafter RP
  load: .

require:
  - smithed_libraries.plugins.companion_mod
  - bolt

pipeline:
  - mecha

# overrides:
#   - > 
#     meta.smithed.versioning = {"scheduled_paths": [
#       "impl/technical/tick", "impl/technical/slow_tick"
#     ]}

meta:
  crafter_mc_version: "1.20.1"
  depends_on:  # used for metadata
    custom-block: "0.1.0"
