extend: "@smithed_libraries/common.yaml"

id: smithed.crafter
name: Smithed Crafter
version: "0.8.1"
description: Native Library for Smithed
author: TheNuclearNexus
minecraft: "1.21"

data_pack:
  name: Smithed Crafter
  load: .
  zipped: true

resource_pack:
  name: Smithed Crafter RP
  load: .
  zipped: true

require:
  - smithed_libraries.plugins.companion_mod
  - bolt
  - beet.contrib.unknown_files

pipeline:
  - mecha
  - smithed_libraries.plugins.crafter

# overrides:
#   - >
#     meta.smithed.versioning = {"scheduled_paths": [
#       "impl/technical/tick", "impl/technical/slow_tick"
#     ]}

output: dist

meta:
  depends_on: # used for metadata
    custom-block: "0.7.1"
  minecraft_version: "1.21.10"
