# auto generated by "smithed_librairies/packs/crafter.py" at build time
# a list of tools, with their max_damage like this : 
# execute 
    # if data entity @s {HandItems:[{id:"minecraft:wooden_sword"}]} 
    # if score $temp1 smithed.data matches 59.. 
    # run function smithed.crafter:impl/block/table/crafting/output/clear_input/delete_tool/sub
