extend: "@smithed_libraries/common.yaml"

id: smithed.custom_block
name: Smithed Custom Block
version: "0.10.0"
description: Native Custom Block Library for Smithed

data_pack:
  name: Smithed Custom Block
  load: .
  pack_format: 101

require:
  - bolt
  - bolt_expressions
  - smithed_libraries.plugins.nbt_literals

pipeline:
  - mecha

