extend: "@smithed_libraries/common.yaml"

id: smithed.damage
name: Smithed Damage 
version: "0.2.0"
description: Native Damage Library for Smithed
minecraft: "1.20"

data_pack:
  name: Smithed Damage
  load: .

require:
  - bolt

pipeline:
  - mecha
